# Config for sway_workspace_names
#
# Format:
# - [pattern, icon]
#
# The pattern will be used to match against the application name.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this list.
---
- [termite, ]
- [github, ]
- [rust, ]
- [google, ]
- [firefox, ]
- [chrome, ]
- [file manager, ]
- [libreoffice calc, ]
- [libreoffice writer, ]
- [libreoffice, ]
- [neovim, ]
- [gthumb, ]
- [menu, ]
- [calculator, ]
- [transmission, ]
- [videostream, ]
- [mpv, ]
- [music, ]
- [disk usage, ]
- [.pdf, ]
